[application]

# App (Project) Name
name = "ullvm"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "uLLVM"

# The application will be served at domain.com/ullvmmy_application/, so we need to modify the base_path to the path where the application will be served
base_path = "ullvm"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["main.css"]

# Javascript code file
script = ["wasm.js", "llvm-json.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
