[application]

# App (Project) Name
name = "ullvm"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "uLLVM"

# The application will be served at domain.com/ullvmmy_application/, so we need to modify the base_path to the path where the application will be served
base_path = "ullvm"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["/ullvm/tailwind.css"]

# Javascript code file
script = [
  "https://cdn.jsdelivr.net/npm/@hpcc-js/wasm@v2.16.2/dist/graphviz.umd.js",
  "https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.49.0/min/vs/loader.min.js",
  "/ullvm/wasm.js",
  "/ullvm/llvm-json.js",
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
